apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-script-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/darksp1der/python-script-devops'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: python-script-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
