name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python ImportLogs.py
        python Solve.py
        python Test.py
        python UnitTest.py

    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    - name: Run Docker container
      run: |
        docker run --rm my-python-app
